// Generated by tools/records.py — do not hand-edit.
// Weekly-scoring records + franchise banners, refreshed by the weekly workflow.
// last built: 2026-09-02
const LEAGUE_RECORDS = {
  "generated": "2026-09-02",
  "season": 2026,
  "weekly": {
    "Adam Stockwell": {
      "high_weeks": 9,
      "low_weeks": 4,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 205.56,
        "week": 10,
        "year": 2023
      },
      "lowest": {
        "score": 58.62,
        "week": 5,
        "year": 2023
      }
    },
    "CJ Woda": {
      "high_weeks": 3,
      "low_weeks": 8,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 157.76,
        "week": 2,
        "year": 2022
      },
      "lowest": {
        "score": 62.38,
        "week": 4,
        "year": 2023
      }
    },
    "Christian Massett": {
      "high_weeks": 4,
      "low_weeks": 4,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 189.34,
        "week": 7,
        "year": 2022
      },
      "lowest": {
        "score": 71.12,
        "week": 9,
        "year": 2024
      }
    },
    "Grant Sawyer": {
      "high_weeks": 4,
      "low_weeks": 5,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 171.06,
        "week": 8,
        "year": 2023
      },
      "lowest": {
        "score": 62.66,
        "week": 2,
        "year": 2022
      }
    },
    "Isaac Douglas": {
      "high_weeks": 2,
      "low_weeks": 5,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 156.88,
        "week": 8,
        "year": 2022
      },
      "lowest": {
        "score": 61.78,
        "week": 3,
        "year": 2024
      }
    },
    "John Lundquist": {
      "high_weeks": 6,
      "low_weeks": 1,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 169.28,
        "week": 5,
        "year": 2025
      },
      "lowest": {
        "score": 79.4,
        "week": 4,
        "year": 2023
      }
    },
    "Kaleb Feahn": {
      "high_weeks": 3,
      "low_weeks": 6,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 156.6,
        "week": 11,
        "year": 2025
      },
      "lowest": {
        "score": 54.26,
        "week": 10,
        "year": 2022
      }
    },
    "Leif Engen": {
      "high_weeks": 4,
      "low_weeks": 7,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 164.12,
        "week": 12,
        "year": 2023
      },
      "lowest": {
        "score": 51.62,
        "week": 6,
        "year": 2024
      }
    },
    "Logan Rezac": {
      "high_weeks": 4,
      "low_weeks": 7,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 185.56,
        "week": 12,
        "year": 2023
      },
      "lowest": {
        "score": 70.64,
        "week": 7,
        "year": 2023
      }
    },
    "Mitchell Max": {
      "high_weeks": 4,
      "low_weeks": 6,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 175.92,
        "week": 2,
        "year": 2022
      },
      "lowest": {
        "score": 59.14,
        "week": 11,
        "year": 2025
      }
    },
    "Noah Thesing": {
      "high_weeks": 2,
      "low_weeks": 1,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 161.48,
        "week": 7,
        "year": 2025
      },
      "lowest": {
        "score": 76.14,
        "week": 10,
        "year": 2022
      }
    },
    "Peter Lundquist": {
      "high_weeks": 11,
      "low_weeks": 2,
      "high_weeks_season": 0,
      "low_weeks_season": 0,
      "highest": {
        "score": 182.46,
        "week": 5,
        "year": 2022
      },
      "lowest": {
        "score": 80.66,
        "week": 8,
        "year": 2023
      }
    }
  },
  "achievements": {
    "Adam Stockwell": [
      {
        "icon": "\ud83c\udfc6",
        "label": "Champion",
        "year": 2025,
        "tier": "champ",
        "note": ""
      },
      {
        "icon": "\ud83e\udd48",
        "label": "Runner-Up",
        "year": 2023,
        "tier": "silver",
        "note": ""
      },
      {
        "icon": "\ud83e\udd47",
        "label": "#1 Seed",
        "year": 2025,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83d\udcca",
        "label": "Scoring Title",
        "year": 2025,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf96\ufe0f",
        "label": "West Title",
        "year": 2025,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2024,
        "tier": "minor",
        "note": ""
      }
    ],
    "CJ Woda": [
      {
        "icon": "\ud83c\udf96\ufe0f",
        "label": "East Title",
        "year": 2024,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2024,
        "tier": "minor",
        "note": ""
      }
    ],
    "Christian Massett": [
      {
        "icon": "\ud83e\udd48",
        "label": "Runner-Up",
        "year": 2024,
        "tier": "silver",
        "note": ""
      },
      {
        "icon": "\ud83c\udfaf",
        "label": "Cinderella",
        "year": 2024,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2022,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2025,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83d\udebd",
        "label": "Last Place",
        "year": 2023,
        "tier": "dishonor",
        "note": ""
      }
    ],
    "Grant Sawyer": [
      {
        "icon": "\ud83c\udf96\ufe0f",
        "label": "East Title",
        "year": 2023,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83d\udcca",
        "label": "Scoring Title",
        "year": 2023,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2023,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83d\udebd",
        "label": "Last Place",
        "year": 2022,
        "tier": "dishonor",
        "note": ""
      }
    ],
    "Isaac Douglas": [
      {
        "icon": "\ud83e\udd48",
        "label": "Runner-Up",
        "year": 2022,
        "tier": "silver",
        "note": ""
      },
      {
        "icon": "\ud83c\udf96\ufe0f",
        "label": "East Title",
        "year": 2022,
        "tier": "major",
        "note": ""
      }
    ],
    "John Lundquist": [
      {
        "icon": "\ud83c\udf96\ufe0f",
        "label": "East Title",
        "year": 2025,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2023,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2024,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2025,
        "tier": "minor",
        "note": ""
      }
    ],
    "Kaleb Feahn": [
      {
        "icon": "\ud83c\udfc6",
        "label": "Champion",
        "year": 2023,
        "tier": "champ",
        "note": ""
      },
      {
        "icon": "\ud83c\udfaf",
        "label": "Cinderella",
        "year": 2023,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2024,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2025,
        "tier": "minor",
        "note": ""
      }
    ],
    "Leif Engen": [
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2023,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83d\udebd",
        "label": "Last Place",
        "year": 2024,
        "tier": "dishonor",
        "note": ""
      }
    ],
    "Logan Rezac": [
      {
        "icon": "\ud83e\udd47",
        "label": "#1 Seed",
        "year": 2023,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf96\ufe0f",
        "label": "West Title",
        "year": 2023,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83e\udd47",
        "label": "#1 Seed",
        "year": 2024,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf96\ufe0f",
        "label": "West Title",
        "year": 2024,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2023,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2024,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83d\udc57",
        "label": "The Dress",
        "year": 2025,
        "tier": "dishonor",
        "note": ""
      }
    ],
    "Mitchell Max": [
      {
        "icon": "\ud83e\udd48",
        "label": "Runner-Up",
        "year": 2025,
        "tier": "silver",
        "note": ""
      },
      {
        "icon": "\ud83c\udfaf",
        "label": "Cinderella",
        "year": 2025,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2023,
        "tier": "minor",
        "note": ""
      }
    ],
    "Noah Thesing": [
      {
        "icon": "\ud83c\udfc6",
        "label": "Champion",
        "year": 2024,
        "tier": "champ",
        "note": ""
      },
      {
        "icon": "\ud83c\udfaf",
        "label": "Cinderella",
        "year": 2024,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2022,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2023,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2025,
        "tier": "minor",
        "note": ""
      }
    ],
    "Peter Lundquist": [
      {
        "icon": "\ud83c\udfc6",
        "label": "Champion",
        "year": 2022,
        "tier": "champ",
        "note": ""
      },
      {
        "icon": "\ud83e\udd47",
        "label": "#1 Seed",
        "year": 2022,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83d\udcca",
        "label": "Scoring Title",
        "year": 2022,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf96\ufe0f",
        "label": "West Title",
        "year": 2022,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83d\udcca",
        "label": "Scoring Title",
        "year": 2024,
        "tier": "major",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2024,
        "tier": "minor",
        "note": ""
      },
      {
        "icon": "\ud83c\udf9f\ufe0f",
        "label": "Playoff Berth",
        "year": 2025,
        "tier": "minor",
        "note": ""
      }
    ]
  }
};
