"""Regenerate the standings table on home.html from live ESPN data.

Content between <!-- STANDINGS:start --> and <!-- STANDINGS:end --> is replaced.
Run standalone or from main.py; safe to run any time (preseason = everyone 0-0).
"""
import re
from lib import espn, load_env, ROOT

START = "<!-- STANDINGS:start -->"
END = "<!-- STANDINGS:end -->"


def _name(s):
    parts = (s or "").split()
    fixed = []
    for p in parts:
        fixed.append("CJ" if p.lower() == "cj" else p[:1].upper() + p[1:].lower())
    return " ".join(fixed)


def _standings(season):
    d = espn(["mTeam", "mSettings"], season)
    members = {m["id"]: _name(f'{m.get("firstName","")} {m.get("lastName","")}')
               for m in d.get("members", [])}
    rows = []
    for t in d.get("teams", []):
        rec = t.get("record", {}).get("overall", {})
        owner = members.get(t.get("primaryOwner")) \
            or members.get((t.get("owners") or [None])[0]) or ""
        rows.append({
            "team": (t.get("name") or "").strip(),
            "owner": owner,
            "w": rec.get("wins", 0), "l": rec.get("losses", 0), "t": rec.get("ties", 0),
            "pf": round(rec.get("pointsFor", 0.0), 1),
            "tid": t.get("id", 99),
        })
    played = any(r["w"] or r["l"] for r in rows)
    if played:
        rows.sort(key=lambda r: (-r["w"], -r["pf"]))
    else:
        rows.sort(key=lambda r: r["tid"])   # league order, stable, resets Week 1
    return rows, played, d.get("status", {}).get("currentMatchupPeriod", 1)


def _html(season):
    rows, played, week = _standings(season)
    label = f"{season} Standings" if played else f"{season} Season"
    tag = f"Week {week}" if played else "Draft complete — season opens Week 1"
    # Leader and last place are marked with a row class the stylesheet turns
    # into a 2px left border — never a background fill.
    tr = []
    for i, r in enumerate(rows, 1):
        cls = ""
        if played and i == 1:
            cls = ' class="row-hi"'
        elif played and i == len(rows):
            cls = ' class="row-lo"'
        tr.append(f'<tr{cls}><td><span class="rank-num">{i}</span></td>'
                  f'<td class="strong">{r["owner"]}</td>'
                  f'<td class="muted">{r["team"]}</td>'
                  f'<td class="strong">{r["w"]}</td><td>{r["l"]}</td>'
                  f'<td>{r["pf"] if played else "&ndash;"}</td></tr>')
    return (
        f'{START}\n'
        f'  <!-- table below is generated by tools/homepage.py — do not hand-edit -->\n'
        f'  <section class="section">\n'
        f'    <span class="eyebrow">Standings</span>\n'
        f'    <h2 class="section-title">{label}</h2>\n'
        f'    <p class="section-sub">{tag}</p>\n'
        f'    <div class="table-scroll narrow">\n'
        f'      <table class="data-table standings-compact">\n'
        f'        <thead><tr><th>#</th><th>Owner</th><th>Team Name</th><th>W</th><th>L</th><th>PF</th></tr></thead>\n'
        f'        <tbody>\n'
        + "\n".join("          " + x for x in tr) + "\n"
        f'        </tbody>\n      </table>\n    </div>\n  </section>\n'
        f'  {END}'
    )


def update(season):
    load_env()
    f = ROOT / "home.html"
    src = f.read_text()
    block = _html(season)
    if START in src and END in src:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, src, flags=re.S)
    else:  # first run — replace the old hand-written "20xx Standings" section
        new = re.sub(r'  <!-- 20\d\d Standings -->\n  <section class="section"[^\0]*?</section>\n',
                     block + "\n", src, count=1, flags=re.S)
    if new != src:
        f.write_text(new)
        print("home.html standings updated")
    else:
        print("home.html unchanged")


if __name__ == "__main__":
    import sys
    update(int(sys.argv[1]) if len(sys.argv) > 1 else 2026)
